### ISSUE TITLE
Hi, just a question

### ISSUE THREAD

**Issue by ffrasisti** [Lyall/P3RFix#1]
Is there a chance this can do anything to combat the drops in certain parts of tartarus on steam deck?

**Comment by Lyall** [comment]
Probably out of the scope for this project but you could try setting the resolution lower using the custom resolution option. You could also mess with the usual [UE4 engine.ini edits](https://www.pcgamingwiki.com/wiki/Engine:Unreal_Engine_4).

Going to close this issue now though as it's not in the scope.

**Comment by ffrasisti** [comment]
I cant seem to get it to work. Is there any way to set the render scale to say 85 instead of moving by increases of 25%? Steam deck performance on areas with a certain type of light drops unless the resolution scale is lowered. Custom inis would break the GUI. Id rather be able to use the existing render scale slider with less agressive jumps.
 Enabling TSR is out of the question too? I just want to be able to drop the render scale without making it as fugly as a 75% scale which is the lowest drop the game allows. Thanks!
