### ISSUE TITLE
[Feature Request]: Direct3D 11 renderer toggle

### ISSUE THREAD

**Issue by ActualMandM** [Lyall/P3RFix#14]
## Feature Summary:

Adding an option to toggle Direct3D 11 rendering in the config.

### Is your proposal related to a problem?

Yes. You can't use the `-dx11` or `-d3d11` launch parameters to launch the game in D3D11 mode. Given other launch parameters don't seem to work, I'm guessing Atlus decided to either block them or had just removed them all.

### Describe the solution you'd like

Just a simple `Enabled` toggle in the `P3RFix.ini` file for Direct3D 11, which would act as the launch parameters if they happened to work with this game.

**Comment by SandeMC** [comment]
I think I've heard that the launch argument only applies to the Steam version, but doesn't work on the MSStore build yeah

**Comment by ActualMandM** [comment]
I have the Steam version, and it doesn't work there.

**Comment by SandeMC** [comment]
Seen some people claim it does, weird

**Comment by Lyall** [comment]
As far as I know, most WinGDK builds of UE4 games do not support any other renderer than DX12. Though according to these [Microsoft docs](https://learn.microsoft.com/en-us/gaming/gdk/_content/gc/get-started-with-pc-dev/get-started-with-unreal-pc/gc-get-started-with-unreal-pc#using-unreal-427-or-later) it should be possible. 

![image](https://github.com/Lyall/P3RFix/assets/695941/fad364b4-4a4b-4afe-a30c-6980f7e2c650)

Persona 3 Reload ships with version 4.27.2 so it should theoretically be compatible based on what the docs say. Perhaps given that they force ray tracing on at boot causes some sort of incompatibility. As for the Steam version, I can't speak to that as I don't own it.

**Comment by Lyall** [comment]
Hmm, so changing the default RHI to DX11 and disabling ray tracing in `P3R\Platforms\WinGDK\Config\WinGDKEngine.ini` causes the game to launch briefly and then crash. According to the brief flash of RTSS, I can see that it is actually running in DX11 mode but it crashes straight away.

![image](https://github.com/Lyall/P3RFix/assets/695941/15a4104a-cc7c-419f-bb72-2cd71d523478)

**Comment by ActualMandM** [comment]
I just tried changing it in `DefaultEngine.ini` (replacing via Unreal Essentials) and got the same result.

![2024-02-14_08-25-40_CrashReportClient](https://github.com/Lyall/P3RFix/assets/15317421/74f280b0-0d43-45ac-afea-0df39ec840ae)

**Comment by bearoso** [comment]
It's up to the developer whether they build the DX11 module in or not, and even then they'd have to configure it to be visually corrrect. The backend code likely isn't there, so there's not much chance of it working at all.

**Comment by ActualMandM** [comment]
In that case I think I'll close this issue.
