### ISSUE TITLE
[Feature Request] UI Toggle

### ISSUE THREAD

**Issue by SandeMC** [Lyall/P3RFix#16]
## Feature Summary:

A way to toggle the UI without having to resort to ReShade.

### Is your proposal related to a problem?

Nope

### Describe the solution you'd like

Just a way to press a button to hide the UI.

### Describe alternatives you've considered

Already implemented here, but as I've said, I would prefer if it wasn't a ReShade thing: https://www.nexusmods.com/persona3reload/mods/3

(btw can you make an issue form via yml instead? much easier to use)

**Comment by Lyall** [comment]
This is probably out of the scope for P3RFix. Would need to restructure it so that the mod has an input handler and that would be quite a bit of work.

**Comment by SandeMC** [comment]
Close the issue as not planned if you're 100% sure it can't done, then
