### ISSUE TITLE
[Feature Request]: Skip Logos but Keep the Opening Movie

### ISSUE THREAD

**Issue by AmirRasool** [Lyall/P3RFix#22]
## Feature Summary:

A way to keep the skip logos feature while retaining the opening animation (Full Moon, Full Life)

### Is your proposal related to a problem?
No

The logos are all skipped as intended but the opening movie is skipped as well (this is with the P3Rfix test build that was committed earlier today) 

### Describe the solution you'd like

To keep the opening movie intact while still skipping the logos

### Describe alternatives you've considered
Burning my dread

**Comment by ActualMandM** [comment]
P3R Essentials implemented the feature to decide on what to skip, if you want to use that as reference.

https://github.com/AnimatedSwine37/p3rpc.essentials/commit/b7e4d7a874910d1334c771489afde187f3c65fbd

**Comment by ActualMandM** [comment]
Looks to be implemented in 02116a35e638d54210038229286f0289e493289b.

**Comment by Lyall** [comment]
This has been added in [v1.1.2](https://github.com/Lyall/P3RFix/releases).
