### ISSUE TITLE
[Feature Request]: Fixing menu edges texture pixelation at a resolution above 1080p (still present after the upscaling fix)

### ISSUE THREAD

**Issue by KemiYuki** [Lyall/P3RFix#26]
### Describe the solution you'd like

Basically since launch, the in-game menu texture gets extremely pixelated when exiting a sub menu or returning to the game.
I have some screenshot i took i while ago, the problem still persist even after the upscaling fix. This problem happens when playing at a higher resolution than 1080p. Don't skip this issue because it is very annoying when playing, because it affects lots of the ui in game

Screenshots: https://imgur.com/a/nI32iaO

**Comment by Lyall** [comment]
Having a look at this just now and I've been able to partially fix it. Still need to more research though. 

![P3R_2024_02_21_22_49_36_258](https://github.com/Lyall/P3RFix/assets/695941/f3954fa2-e0df-46c3-a774-54f2be13e91c)

**Comment by Lyall** [comment]
Okay, think I've got it working now. 

![P3R_2024_02_21_22_55_20_586](https://github.com/Lyall/P3RFix/assets/695941/2ac4d2f0-661f-4891-a760-337775cbc15a)

**Comment by KemiYuki** [comment]
@Lyall I can confirm that this fix works! I tried on my end and it is perfect for now. A thing that i noticed is the skip to opening intro that probably has a bug (when using SkipTo = 1, it does skip to the opening but it isn't skippable with any button)

**Comment by Lyall** [comment]
> @Lyall I can confirm that this fix works! I tried on my end and it is perfect for now. A thing that i noticed is the skip to opening intro that probably has a bug (when using SkipTo = 1, it does skip to the opening but it isn't skippable with any button)

Yep, I know about that bug and it's been roported in #28. Will try and fix it in the next version.
