### ISSUE TITLE
Fix not Working with Reloaded 2.

### ISSUE THREAD

**Issue by HeppuPlays** [Lyall/P3RFix#29]
I have placed the P3RFix .asi and ini in the Script folder as instructed but nothing is happening.

Everything Say's it should be working. The game is installing with my Reloaded mods just fine but the Fix doesn't seem to be takin any effect.

Or like Now it seems to be Half Working. The menu's are still 60 FPS and the Opening Logo Skips Don't Work. But The  "Pause on Focus Loss" Option Seems to Be working as intended.

**Comment by Lyall** [comment]
Are you using the mod p3rpc.essentials? There might be incompatibility with that given that it uses the same method for skipping the intro.  I can't really test on my end due to Reloaded-II not working with the gamepass version.

**Comment by HeppuPlays** [comment]
didn't work. I tried turning off every single mod I have from Reloaded and still nothing. Just to be Clear  though that i didn't intall it wrong by accident. but I don't need to do anything with the WIN GDK folder right? Or do i still have to put the Dsound ini somewhere within Win64.

**Comment by Lyall** [comment]
I believe you have it setup the correct way. Can you post the contents of `P3RFix.log`?

**Comment by HeppuPlays** [comment]
[P3RFix.log](https://github.com/Lyall/P3RFix/files/14383796/P3RFix.log)

**Comment by Lyall** [comment]
Okay, looks like it's not finding the ini file because it's in the scripts folder. Try moving `PR3Fix.ini` out of that folder and in the same one as `P3R.exe`.

**Comment by HeppuPlays** [comment]
This Seems to have fixed it.

**Comment by Lyall** [comment]
Glad to hear it. I've amended the instructions for the Reloaded 2 section on the README as well.
