### ISSUE TITLE
[Bug]: Game does not launch with P3RFix files

### ISSUE THREAD

**Issue by lewdnasty** [Lyall/P3RFix#33]
## Issue Summary:
P3R won't launch when the files are in the game directory. When the dsound.dll and dsound.ini files are removed, the game will launch but not apply any of the P3RFix.ini files. I can duplicate this issue with both the Steam version and Reloaded-II launch. I've left the .ini file vanilla and modified to a custom resolution, and no matter what, the game will not launch. It will show up in the Task Manager, but simply hang.

## P3RFix & Game Version Numbers:
P3RFix 1.1.4

## Log Files:
No .log file because it won't launch.

## Reproduction:
When adding the dsound.dll and .ini files, the game refuses the launch. Removing them will allow the game to start, with no P3RFix settings applied. As said, the process shows up in the Windows Task Manager with a 0%CPU load and about 2MB of Memory being used. Launched via Steam and Reloaded-II (both with and without administrator access) with no way to get the game to actually start.

EDIT: seems to be related to issue #24 but the poster didn't make it clear what their potential fix was.

**Comment by lewdnasty** [comment]
No luck with renaming sadly.

![image](https://github.com/Lyall/P3RFix/assets/4476501/b60ec36f-24eb-4996-bf3c-5bd5b4ea4a81)

**Comment by Lyall** [comment]
You've got a scripts folder there, does that mean you're using Reloaded II at all?

**Comment by lewdnasty** [comment]
Yes, and I've tried adding the P3RFix.asi to that and launching via Steam as well as Reloaded with and without the .asi file to no avail.

**Comment by Lyall** [comment]
Have you tried following the Reloaded 2 specific instructions in the README to the letter? 

Try deleting `dsound.dll` and `dsound.ini`.
Move `P3RFix.asi`  in to the scripts folder.
Find Persona 3 Reloaded in Reloaded 2.
Go to Edit Application -> Advanced Tools & Options, then hit Deploy ASI Loader.

In theory those steps should work for you. I can't validate it on my end as I don't have a Steam copy but other people have gotten it working.

**Comment by lewdnasty** [comment]
No luck. The game will launch without the dsound .dll and .ini files, but none of the P3RFix.ini changes apply. The intro skip is the benchmark I'm using, but even after getting in-game without the dsound files, no increased FPS or other changes.

**Comment by Lyall** [comment]
If you delete `dsound.dll` and `dsound.ini` then deploy the ASI loader in Reloaded 2, does it create another `dsound.dll` file?

**Comment by lewdnasty** [comment]
No, it does not.

**Comment by Lyall** [comment]
Hmm that's odd. What does your `P3R\Binaries\Win64` folder look like after you've hit deploy ASI loader? It should be copying over Ultimate ASI loader.

**Comment by lewdnasty** [comment]
![image](https://github.com/Lyall/P3RFix/assets/4476501/c988544c-ae2d-4fb8-999d-1d776865ebea)

When deploying the ASI loader, this is how the folder looks.

**Comment by Lyall** [comment]
Sorry for the delay in responding here. I think this is probably more of an issue with Reloaded 2 as opposed to P3RFix. It looks like it's not deploying it's ASI loader properly. Going to close this for now.
