### ISSUE TITLE
Narrow UI isn't properly supported

### ISSUE THREAD

**Issue by SlimDread** [Lyall/P3RFix#4]
The UI does not fill the top and bottom at 4:3
![hqfiXik](https://github.com/Lyall/P3RFix/assets/84397998/451aa53d-5245-4d61-80f3-392b756d1f65)

![wQjk9M4](https://github.com/Lyall/P3RFix/assets/84397998/1cd245ec-406b-41ad-975f-c44604072ebc)

**Comment by Lyall** [comment]
Planning on addressing this in the next release. Bear in mind that it won't be able to add detail where it doesn't exist but it should stop UI elements that would overlap from being cut-off.

**Comment by Lyall** [comment]
Here is how it looks after battle for example. It won't look nearly this good on every part of the UI but it should help quite a bit.

Before:
![P3R_2024_02_03_03_22_42_481](https://github.com/Lyall/P3RFix/assets/695941/5259af1d-40cb-40b3-8f1c-b3006a03b5c5)

After:
![P3R_2024_02_03_03_23_25_105](https://github.com/Lyall/P3RFix/assets/695941/69027b02-ed0e-48fe-93a2-065a24f85886)

**Comment by SlimDread** [comment]
Looks great!

**Comment by SandeMC** [comment]
honestly impressive you can even make 4:3 bearable lol

**Comment by SlimDread** [comment]
I've made and tested a build with your latest commit, is it possible to bring the bustup portrait UI to the bottom and the dark hour calendar to the top?
![h4MH8Ll](https://github.com/Lyall/P3RFix/assets/84397998/ac124769-ab09-4cbe-860a-64e2742679fe)
Also the transitions to fill the entire screen.
![GGUm5gw](https://github.com/Lyall/P3RFix/assets/84397998/9b3406a1-814b-4c17-b67b-b7ce19695ebb)

**Comment by Lyall** [comment]
> I've made and tested a build with your latest commit, is it possible to bring the bustup portrait UI to the bottom and the dark hour calendar to the top?

Probably not. The UI code for this game is super complex. It does a lot of custom stuff, so adjusting individual elements is pretty hard.

> Also the transitions to fill the entire screen.

This part I do want to try and address. I've found the relevant part of code but getting it to span the entire screen has proven tricky. Even this part is complex, they have at least 8 different distinct types of screen fades!

**Comment by DPS2004** [comment]
For resolutions that are close to 16:9, like 16:10, would it be possible to just scale up the portraits slightly instead of moving them? This runs great on my steam deck, but the portrait thing is bothering me as well

**Comment by Lyall** [comment]
> For resolutions that are close to 16:9, like 16:10, would it be possible to just scale up the portraits slightly instead of moving them? This runs great on my steam deck, but the portrait thing is bothering me as well

I don't really have the fine control over the UI. It's very complex. What I could do though is add a stretched HUD option. The mild vertical stretching at 16:10 might be more bearable than the gaps.

**Comment by Lyall** [comment]
This is mostly fixed now as of v1.1.0.
