### ISSUE TITLE
[Bug]: Render Texture Resolution not working properly anymore

### ISSUE THREAD

**Issue by DeltaQuartz** [Lyall/P3RFix#48]
Issue Summary:

So as of the latest version of the game, even with the updated p3r fix, render texture resolution does not work. I have added screenshots of the low texture issues and also my reloaded mod list. Also trying the none reloaded one, it works on some stuff like persona models but not others like character models in the summon menu.

P3RFix & Game Version Numbers:
P3RFix Version 1.2.2 and Game is the latest version 1.07

Log Files:
both the reloaded and none reloaded ver logs.
[P3RFix.log](https://github.com/user-attachments/files/17008054/P3RFix.log)
[P3RFix.log](https://github.com/user-attachments/files/17008055/P3RFix.log)

Reproduction:
I used 135 screen percentage and 2 for render texture resolution multiplier
![Screenshot 2024-09-15 201149](https://github.com/user-attachments/assets/4c6ccda4-4f70-4ea5-8b67-de473c7609db)
![Screenshot 2024-09-15 201156](https://github.com/user-attachments/assets/9e63aed5-0519-4fb2-b24d-89836e655dd9)
![Screenshot 2024-09-15 201242](https://github.com/user-attachments/assets/31f692f7-5a55-40e5-aca3-1f72380d1eba)
![Screenshot 2024-09-15 201556](https://github.com/user-attachments/assets/da71840c-3bdc-40d1-a5f8-7bef5529d164)
![Screenshot 2024-09-15 202342](https://github.com/user-attachments/assets/9429cef4-2140-447a-9946-6b62917eefef)

**Comment by DeltaQuartz** [comment]
okay its worse apparently cause both the normal and reloaded versions now have the same issue (shown in the last screenshot)

**Comment by Lyall** [comment]
Hmm there's been no change to that section of code in the latest update to P3RFix. Perhaps it changed in the Aegis update? I'll investigate further.

**Comment by Lyall** [comment]
Should be fixed in [v1.2.3](https://github.com/Lyall/P3RFix/releases)
