### ISSUE TITLE
FOV increase makes it so in battle the UI is not where it's suppose to be

### ISSUE THREAD

**Issue by Brandonspikes** [Lyall/P3RFix#5]
So while in combat the UI puts an outline around the character, the more zoomed out with the FOV mod the more the outline is distanced from the characters.

Is there any way to make it so the FOV is only zoomed outside of combat, I think that would be the only way to fix the issue

**Comment by Brandonspikes** [comment]
Default FOV

![normal FOV](https://github.com/Lyall/P3RFix/assets/81451059/c98f44d1-b6f9-426e-86a9-81c87251824d)

vs +20 FOV
![20FOV](https://github.com/Lyall/P3RFix/assets/81451059/10669eb5-50e8-43d6-b1dd-f02536515049)

**Comment by Lyall** [comment]
It looks like those outlines are actually rendered as part of the UI canvas. Therefore they expect the characters to be in very specific parts of the screen. It would be a lot of work to try and only modify the FOV when outside of battle and there could be other stuff that breaks, so I'll be removing this feature in the next release.

**Comment by Brandonspikes** [comment]
I wonder if there's a way to disable that specific UI element of the character outlines, I think that would make the FOV mod viable without causing any visual glitches.
