### ISSUE TITLE
Text and map cutting off?

### ISSUE THREAD

**Issue by waddles777** [Lyall/P3RFix#8]
<img width="1279" alt="Screenshot 2024-02-05 181007" src="https://github.com/Lyall/P3RFix/assets/159055353/fe761884-a1fa-46e5-8f17-a0a5b855e7f1">
<img width="319" alt="Screenshot 2024-02-05 181546" src="https://github.com/Lyall/P3RFix/assets/159055353/36e34de7-300f-4052-8d71-dcdf2828a479">

It seems the bottom half of my screen has been cut off, and im using the right resolution for my pc. 
Also, im on boderless fullscreen. When im on just fullscreen my screen doesnt cut off but the quality is a lot worse.

**Comment by Lyall** [comment]
Can you post your `P3RFix.log` file? It may be in the main game folder and not in the Binaries folder btw depending on how the game was launched.

**Comment by waddles777** [comment]
[P3RFix.log](https://github.com/Lyall/P3RFix/files/14185797/P3RFix.log)

I'm not very tech savvy so i might've done something wrong.. Sorry!

**Comment by Lyall** [comment]
Hmm I can't seem to replicate the issue on my end. Can you try this build that has some additional logging? Then post your `P3RFix.log` file.

[P3RFix_v1.0.2_test.zip](https://github.com/Lyall/P3RFix/files/14199577/P3RFix_v1.0.2_test.zip)

**Comment by Lyall** [comment]
This should be addressed in v1.1.0. I was able to figure out why parts of the UI were getting cut off.

**Comment by Lyall** [comment]
This should be fixed now. If you still have the same issue feel free to reopen/create a new issue.
