### ISSUE TITLE
It's not working for me. 

### ISSUE THREAD

**Issue by Thetomiya** [Lyall/P3RFix#9]
I play through gamepass. I copied the P3RFix-master folder to Persona 3 Reload\Content and the game is still 16:9.
I also tried to copy not the P3RFix-master folder, but its contents, and specified my resolution in the P3RFix.ini file, but it didn't work. I also tried to do the above in other folders, such as \Persona 3 Reload\Content\Engine\Binaries, 
\Persona 3 Reload, 
\Persona 3 Reload, but nothing worked.
(I also tried to change the resolution using hex editor, but it didn't work either). What should I do?

**Comment by SandeMC** [comment]
...Use the release, not the source code...

**Comment by Lyall** [comment]
Yes, as @SandeMC said. You need to download the release build not the source code. You can find it here.
![image](https://github.com/Lyall/P3RFix/assets/695941/075aad43-2117-412c-beeb-88094df0e19f)

Then click on the release zip.
![image](https://github.com/Lyall/P3RFix/assets/695941/86e6d70a-4458-4ec5-89ae-0934fc1efc75)

**Comment by Thetomiya** [comment]
Thank you =)
